id: P1483B981
initial_creation_type: input
source_metadata:
  title: Gampopa Series
  language: bo
  description: 'Texts by and about Gampopa Sonam Rinchen (sgam po pa bsod nams rin
    chen, 1079–1153), the famous master credited with founding the Kagyü school of
    Tibetan Buddhism:'
  volume:
    41c53b08f4d74f45bc4f9d1c5753918b:
      title: A Combined Guru Yoga for Marpa, Mila, and Gampopa
      parent: Guru Yoga
    1d77f03e8972473d8a086ada5c6ce889:
      title: 'A Drop of Jewels: A Guru Yoga for Lord Gampopa'
      parent: Guru Yoga
    24147fade6264578a1a5721610ade275:
      title: 'Vajra Net: The Ancillary Preliminary and Concluding Practices for the
        Three Drops, the Guru Yogas for Venerable Marpa, Mila, and Gampopa'
      parent: Guru Yoga
    2c0f36d82f064988ae0653ecfdab0b3d:
      title: 'A Precious Garland for the Supreme Path of the Three Types of Individual:
        The Root of Dakpo''s Four Dharmas'
      parent: Lamrim
    1a633d3192194fa0ae73a22beb7d4d4f:
      title: 'The Melody of Complete Accomplishment: A Prayer to Those Praised as
        Ornaments of the Practice Lineage'
      parent: Prayers
created_at: '2022-02-28T23:21:13.677049'
last_modified_at: '2022-02-28T23:21:13.677051'
